import Head from 'next/head'
import { getData } from '../utils/tools'
import { useState } from 'react'
import Card from '../components/Card'
import Form from '../components/Form'

export default function Home({listUser}) {
   const [userState, setUserState]=
   useState(listUser)
  return (
    <>
      <Head>
        <title>Usuarios Cebar SAS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>Usuarios Cebar SAS</header>
      <main>
      <Form fun={setUserState}/>
        <div>
        {userState.map(user => <Card key={user.id} user={user} fun={setUserState} />)}
        </div>
      </main>
    </>
  )
}


export async function getServerSideProps(){
   try {
      const jsonUsers = await getData()
      
      return{
         props: {
            listUser : jsonUsers
         }
      }
   } catch (error) {
      console.log(error)
      return{
         props: {
            listUser: []
         }
      }
   }
}

